name: Building and deploying Angular application
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install NPM Dependencies
        run: npm i

      - name: Deploy to gh pages
        run: npx ng deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
